version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  target-branch: 2.x
  versioning-strategy: widen
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
