name: auto-merge

on: [pull_request_target]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          target: minor
          github-token: ${{ secrets.PAT }}
