name: Continuous Integration (PHP 8)

on:
  pull_request:
  push:
    branches:
      - "2.x"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: 'echo "::set-output name=directory::$(composer config cache-dir)"'

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-composer-cache"

      - name: "Composer install"
        run: "composer install --ignore-platform-reqs"

      - name: "Run tests"
        run: "php vendor/bin/phpunit"
